"""
P2 Phases 3-8: Feature Pipeline + Model Training + Test Scoring
=================================================================
OPTIMISED: All features computed in DuckDB SQL for speed.
No SequenceMatcher (too slow on 35M pairs).

Feature set (17 features, all computed in DuckDB):
  Name:    exact_match, jaccard, prefix4_match, first_token_match, len_diff, len_ratio, common_token_count
  Address: exact_match, jaccard, number_overlap, len_diff, len_ratio, common_token_count
  Country: exact_match
  Cross:   name_trigram_jaccard (approx via 3-char prefix), addr_trigram_jaccard (approx)
  Meta:    source_is_s3
"""
import json
import os
import sys
import time
import duckdb
import numpy as np

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
NORM_DIR = os.path.join(REPO, "outputs", "person1_step1", "normalized")
GT_PATH = os.path.join(REPO, "outputs", "person1_step1", "train_ground_truth_reconstructed.tsv")
CAND_DIR = os.path.join(REPO, "P2", "data", "candidates")
FEAT_DIR = os.path.join(REPO, "P2", "data", "features")
PROC_DIR = os.path.join(REPO, "P2", "data", "processed")
MODEL_DIR = os.path.join(REPO, "P2", "models")
REPORT_DIR = os.path.join(REPO, "P2", "reports")
TMP_DIR = os.path.join(REPO, "P2", "data", "duckdb_feat_tmp")

# Test candidate paths
TEST_S2_CAND = os.path.join(REPO, "outputs", "person1_step1", "test_candidate_pairs_s2.tsv")
TEST_S3_CAND = os.path.join(REPO, "outputs", "person1_step1", "test_candidate_pairs_s3.tsv")

# Train candidate paths (generated by Phase 2)
TRAIN_S2_CAND = os.path.join(CAND_DIR, "train_strategy_b_candidates_s2.tsv")
TRAIN_S3_CAND = os.path.join(CAND_DIR, "train_strategy_b_candidates_s3.tsv")

SEED = 42

for d in [FEAT_DIR, PROC_DIR, MODEL_DIR, REPORT_DIR, TMP_DIR]:
    os.makedirs(d, exist_ok=True)


# =====================================================================
# DuckDB UDFs for token-level features
# =====================================================================

FEATURE_SQL = """
    -- Name features
    CASE WHEN s1.business_name <> '' AND s1.business_name = tgt.business_name THEN 1.0 ELSE 0.0 END AS name_exact_match,
    jaro_winkler_similarity(COALESCE(s1.business_name,''), COALESCE(tgt.business_name,'')) / 100.0 AS name_jaro_winkler,
    CASE WHEN LENGTH(COALESCE(s1.business_name,'')) >= 2 AND LENGTH(COALESCE(tgt.business_name,'')) >= 2 THEN jaccard(COALESCE(s1.business_name,''), COALESCE(tgt.business_name,'')) ELSE 0.0 END AS name_jaccard,
    CASE WHEN LENGTH(s1.business_name) >= 4 AND LENGTH(tgt.business_name) >= 4
              AND LEFT(s1.business_name, 4) = LEFT(tgt.business_name, 4) THEN 1.0 ELSE 0.0 END AS prefix4_match,
    CASE WHEN s1.business_name <> '' AND tgt.business_name <> ''
              AND SPLIT_PART(s1.business_name, ' ', 1) = SPLIT_PART(tgt.business_name, ' ', 1) THEN 1.0 ELSE 0.0 END AS first_token_match,
    CAST(ABS(LENGTH(COALESCE(s1.business_name,'')) - LENGTH(COALESCE(tgt.business_name,''))) AS DOUBLE) AS name_len_diff,
    CASE WHEN LENGTH(s1.business_name) > 0 AND LENGTH(tgt.business_name) > 0
         THEN CAST(LEAST(LENGTH(s1.business_name), LENGTH(tgt.business_name)) AS DOUBLE) / GREATEST(LENGTH(s1.business_name), LENGTH(tgt.business_name))
         ELSE 0.0 END AS name_len_ratio,
    -- Address features
    CASE WHEN s1.business_address <> '' AND s1.business_address = tgt.business_address THEN 1.0 ELSE 0.0 END AS address_exact_match,
    jaro_winkler_similarity(COALESCE(s1.business_address,''), COALESCE(tgt.business_address,'')) / 100.0 AS address_jaro_winkler,
    CASE WHEN LENGTH(COALESCE(s1.business_address,'')) >= 2 AND LENGTH(COALESCE(tgt.business_address,'')) >= 2 THEN jaccard(COALESCE(s1.business_address,''), COALESCE(tgt.business_address,'')) ELSE 0.0 END AS address_jaccard,
    CAST(ABS(LENGTH(COALESCE(s1.business_address,'')) - LENGTH(COALESCE(tgt.business_address,''))) AS DOUBLE) AS address_len_diff,
    CASE WHEN LENGTH(s1.business_address) > 0 AND LENGTH(tgt.business_address) > 0
         THEN CAST(LEAST(LENGTH(s1.business_address), LENGTH(tgt.business_address)) AS DOUBLE) / GREATEST(LENGTH(s1.business_address), LENGTH(tgt.business_address))
         ELSE 0.0 END AS address_len_ratio,
    -- House number overlap
    CASE WHEN regexp_extract(COALESCE(s1.business_address,''), '\\b[0-9]+\\b', 0) <> ''
              AND regexp_extract(COALESCE(tgt.business_address,''), '\\b[0-9]+\\b', 0) <> ''
              AND regexp_extract(s1.business_address, '\\b[0-9]+\\b', 0) = regexp_extract(tgt.business_address, '\\b[0-9]+\\b', 0)
         THEN 1.0 ELSE 0.0 END AS address_first_number_match,
    -- Country
    CASE WHEN s1.country <> '' AND s1.country = tgt.country THEN 1.0 ELSE 0.0 END AS country_match,
    -- Lengths for model context
    CAST(LENGTH(COALESCE(s1.business_name,'')) AS DOUBLE) AS s1_name_len,
    CAST(LENGTH(COALESCE(tgt.business_name,'')) AS DOUBLE) AS tgt_name_len,
    CAST(LENGTH(COALESCE(s1.business_address,'')) AS DOUBLE) AS s1_addr_len,
    CAST(LENGTH(COALESCE(tgt.business_address,'')) AS DOUBLE) AS tgt_addr_len
"""

FEATURE_NAMES = [
    "name_exact_match", "name_jaro_winkler", "name_jaccard",
    "prefix4_match", "first_token_match", "name_len_diff", "name_len_ratio",
    "address_exact_match", "address_jaro_winkler", "address_jaccard",
    "address_len_diff", "address_len_ratio", "address_first_number_match",
    "country_match",
    "s1_name_len", "tgt_name_len", "s1_addr_len", "tgt_addr_len",
    "source_is_s3",
]


def load_entities(con):
    """Load train + test normalized entities into DuckDB."""
    print("Loading normalized entities...")
    t0 = time.time()

    for name, path in [
        ("s1", os.path.join(NORM_DIR, "train_source1_normalized.tsv")),
        ("s2", os.path.join(NORM_DIR, "train_source2_normalized.tsv")),
        ("s3", os.path.join(NORM_DIR, "train_source3_normalized.tsv")),
    ]:
        con.execute(f"""
            CREATE OR REPLACE TABLE {name} AS
            SELECT entity_id, business_name, business_address, country
            FROM read_csv('{path}', delim='\\t', header=true, all_varchar=true)
        """)
        cnt = con.execute(f"SELECT COUNT(*) FROM {name}").fetchone()[0]
        print(f"  Train {name.upper()}: {cnt:,}")

    for name, path in [
        ("test_s1", os.path.join(NORM_DIR, "test_source1_normalized.tsv")),
        ("test_s2", os.path.join(NORM_DIR, "test_source2_normalized.tsv")),
        ("test_s3", os.path.join(NORM_DIR, "test_source3_normalized.tsv")),
    ]:
        con.execute(f"""
            CREATE OR REPLACE TABLE {name} AS
            SELECT entity_id, business_name, business_address, country
            FROM read_csv('{path}', delim='\\t', header=true, all_varchar=true)
        """)
        cnt = con.execute(f"SELECT COUNT(*) FROM {name}").fetchone()[0]
        print(f"  Test {name.upper()}: {cnt:,}")

    print(f"  Done ({time.time() - t0:.1f}s)")


def generate_features_sql(con, cand_path, s1_table, tgt_table, source_is_s3, out_path, has_label=False):
    """Generate features for all pairs in one DuckDB SQL pass."""
    label_col = ", CAST(c.label AS INT) AS label" if has_label else ""
    source_val = "1" if source_is_s3 else "0"

    print(f"  Generating features: {os.path.basename(out_path)}...")
    t0 = time.time()

    con.execute(f"""
        COPY (
            SELECT
                c.source1_entity_id,
                c.matched_entity_id,
                {FEATURE_SQL},
                {source_val} AS source_is_s3
                {label_col}
            FROM read_csv('{cand_path}', delim='\\t', header=true, all_varchar=true) c
            LEFT JOIN {s1_table} s1 ON c.source1_entity_id = s1.entity_id
            LEFT JOIN {tgt_table} tgt ON c.matched_entity_id = tgt.entity_id
        )
        TO '{out_path}'
        WITH (FORMAT CSV, DELIMITER '\\t', HEADER)
    """)

    cnt = con.execute(f"""
        SELECT COUNT(*) FROM read_csv('{out_path}', delim='\\t', header=true, all_varchar=true)
    """).fetchone()[0]
    size_mb = os.path.getsize(out_path) / (1024 * 1024)
    print(f"    Rows: {cnt:,}, Size: {size_mb:.1f} MB ({time.time() - t0:.1f}s)")
    return cnt


def main():
    t_global = time.time()

    # Prerequisites
    for f in [TRAIN_S2_CAND, TRAIN_S3_CAND]:
        if not os.path.isfile(f):
            print(f"ERROR: Missing {f}. Run phase2_train_recall.py first.")
            sys.exit(1)

    con = duckdb.connect()
    con.execute("SET memory_limit='4GB'")
    con.execute("SET threads=4")
    con.execute("SET preserve_insertion_order=false")
    con.execute(f"SET temp_directory='{TMP_DIR}'")

    load_entities(con)

    # ================================================================
    # Smoke test (100 rows)
    # ================================================================
    print("\n" + "="*60)
    print("SMOKE TEST (100 rows)")
    print("="*60)

    smoke_path = os.path.join(FEAT_DIR, "smoke_test.tsv")
    con.execute(f"""
        COPY (
            SELECT * FROM read_csv('{TRAIN_S2_CAND}', delim='\\t', header=true, all_varchar=true)
            LIMIT 100
        )
        TO '{smoke_path}'
        WITH (FORMAT CSV, DELIMITER '\\t', HEADER)
    """)
    smoke_feat_path = os.path.join(FEAT_DIR, "smoke_test_features.tsv")
    n_smoke = generate_features_sql(con, smoke_path, "s1", "s2", False, smoke_feat_path, has_label=True)

    verify = con.execute(f"""
        SELECT
            COUNT(*),
            SUM(label) AS pos,
            AVG(name_jaro_winkler) AS avg_jw,
            MIN(name_exact_match),
            MAX(name_exact_match)
        FROM read_csv('{smoke_feat_path}', delim='\\t', header=true)
    """).fetchone()
    print(f"  Smoke: rows={verify[0]}, pos={verify[1]}, avg_jw={verify[2]:.4f}")
    assert verify[0] == 100, f"Expected 100, got {verify[0]}"
    print("  SMOKE TEST PASSED OK")

    # ================================================================
    # Phase 3+4: Training features
    # ================================================================
    print("\n" + "="*60)
    print("PHASE 3+4: TRAINING FEATURE GENERATION")
    print("="*60)

    t0 = time.time()
    train_feat_path = os.path.join(FEAT_DIR, "train_features_combined.tsv")
    
    if os.path.isfile(train_feat_path):
        print(f"  Found existing {train_feat_path}, skipping Phase 3+4 generation.")
    else:
        s2_feat_path = os.path.join(FEAT_DIR, "train_features_s2.tsv")
        s3_feat_path = os.path.join(FEAT_DIR, "train_features_s3.tsv")
    
        n_s2 = generate_features_sql(con, TRAIN_S2_CAND, "s1", "s2", False, s2_feat_path, has_label=True)
        n_s3 = generate_features_sql(con, TRAIN_S3_CAND, "s1", "s3", True, s3_feat_path, has_label=True)
    
        # Combine
        print("\n  Combining S2 + S3 features...")
        con.execute(f"""
            COPY (
                SELECT * FROM read_csv('{s2_feat_path}', delim='\\t', header=true)
                UNION ALL
                SELECT * FROM read_csv('{s3_feat_path}', delim='\\t', header=true)
            )
            TO '{train_feat_path}'
            WITH (FORMAT CSV, DELIMITER '\\t', HEADER)
        """)
        print(f"  Feature generation ({time.time() - t0:.1f}s)")

    # Summary
    stats = con.execute(f"""
        SELECT
            COUNT(*) AS total,
            SUM(label) AS positives,
            COUNT(*) - SUM(label) AS negatives,
            COUNT(DISTINCT source1_entity_id) AS unique_s1,
            AVG(label) * 100 AS pos_rate_pct
        FROM read_csv('{train_feat_path}', delim='\\t', header=true)
    """).fetchone()
    total, positives, negatives, unique_s1, pos_rate = stats
    print(f"\n  Training data summary:")
    print(f"    Total pairs: {total:,}")
    print(f"    Positives: {positives:,}")
    print(f"    Negatives: {negatives:,}")
    print(f"    Positive rate: {pos_rate:.4f}%")
    print(f"    Unique S1: {unique_s1:,}")
    print(f"  Feature generation ({time.time() - t0:.1f}s)")

    # ================================================================
    # Phase 5: Model training
    # ================================================================
    print("\n" + "="*60)
    print("PHASE 5: MODEL TRAINING (LightGBM)")
    print("="*60)

    import lightgbm as lgb
    from sklearn.metrics import average_precision_score

    t0 = time.time()
    model_path = os.path.join(MODEL_DIR, "lgbm_baseline_v1.txt")
    
    if os.path.isfile(model_path):
        print(f"  Found existing model at {model_path}, skipping training.")
        model = lgb.Booster(model_file=model_path)
    else:
        print("  Loading features into numpy...")

        col_expr = ", ".join([f"CAST({c} AS DOUBLE) AS {c}" for c in FEATURE_NAMES])
        data = con.execute(f"""
            SELECT
                source1_entity_id,
                matched_entity_id,
                {col_expr},
                CAST(label AS INT) AS label
            FROM read_csv('{train_feat_path}', delim='\\t', header=true)
            WHERE CAST(label AS INT) = 1 OR random() < 0.33
        """).fetchnumpy()

        s1_ids = data["source1_entity_id"]
        t_ids = data["matched_entity_id"]
        y = data["label"].astype(np.int32)
        X = np.column_stack([data[c].astype(np.float32) for c in FEATURE_NAMES])

        print(f"  X shape: {X.shape}, positives: {y.sum():,}, negatives: {(1-y).sum():,}")

        # Stratified train/val split
        X_train, X_val, y_train, y_val, idx_train, idx_val = manual_train_test_split(
            X, y, np.arange(len(y)), test_size=0.15, random_state=SEED
        )
        print(f"  Train: {len(X_train):,} (pos={y_train.sum():,})")
        print(f"  Val:   {len(X_val):,} (pos={y_val.sum():,})")

        # LightGBM
        lgb_params = {
            "objective": "binary",
            "metric": "binary_logloss",
            "verbosity": -1,
            "num_threads": 4,
            "seed": SEED,
            "learning_rate": 0.05,
            "num_leaves": 63,
            "max_depth": -1,
            "min_child_samples": 50,
            "feature_fraction": 0.8,
            "bagging_fraction": 0.8,
            "bagging_freq": 5,
            "scale_pos_weight": float((1 - y_train.mean()) / max(y_train.mean(), 1e-9)),
            "is_unbalance": False,
        }

        train_ds = lgb.Dataset(X_train, y_train, feature_name=FEATURE_NAMES)
        val_ds = lgb.Dataset(X_val, y_val, feature_name=FEATURE_NAMES, reference=train_ds)

        print("  Training...")
        model = lgb.train(
            lgb_params, train_ds,
            num_boost_round=500,
            valid_sets=[val_ds],
            callbacks=[lgb.log_evaluation(100)],
        )

        model.save_model(model_path)
        print(f"  Model saved: {model_path}")

        # Free training arrays
        del X, y, X_train, X_val, y_train, y_val, data

    # Validation
    val_proba = model.predict(X_val)
    pr_auc = manual_average_precision_score(y_val, val_proba)
    print(f"\n  PR-AUC: {pr_auc:.4f}")

    # Threshold analysis
    print("\n  --- Threshold Analysis ---")
    thresholds = [0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90]
    threshold_results = []
    for t in thresholds:
        preds = (val_proba >= t).astype(int)
        tp = int(((preds == 1) & (y_val == 1)).sum())
        fp = int(((preds == 1) & (y_val == 0)).sum())
        fn = int(((preds == 0) & (y_val == 1)).sum())
        tn = int(((preds == 0) & (y_val == 0)).sum())
        prec = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        rec = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1 = 2 * prec * rec / (prec + rec) if (prec + rec) > 0 else 0.0
        f05 = (1.25 * prec * rec) / (0.25 * prec + rec) if (0.25 * prec + rec) > 0 else 0.0
        threshold_results.append({
            "threshold": t, "precision": round(prec, 4), "recall": round(rec, 4),
            "f1": round(f1, 4), "f0.5": round(f05, 4),
            "tp": tp, "fp": fp, "fn": fn, "tn": tn,
        })
        print(f"    t={t:.2f}: P={prec:.4f} R={rec:.4f} F1={f1:.4f} F0.5={f05:.4f} TP={tp:,} FP={fp:,} FN={fn:,}")

    # Feature importance
    importance = model.feature_importance(importance_type="gain")
    feat_imp = sorted(zip(FEATURE_NAMES, importance.tolist()), key=lambda x: -x[1])
    print("\n  --- Feature Importance (Gain) ---")
    for fname, fgain in feat_imp:
        print(f"    {fname:30s}: {fgain:.1f}")

    print(f"\n  Training complete ({time.time() - t0:.1f}s)")

    # ================================================================
    # Phase 7: Test scoring
    # ================================================================
    print("\n" + "="*60)
    print("PHASE 7: TEST SCORING")
    print("="*60)

    for tgt, cand_path, s1_tbl, tgt_tbl, is_s3 in [
        ("s2", TEST_S2_CAND, "test_s1", "test_s2", False),
        ("s3", TEST_S3_CAND, "test_s1", "test_s3", True),
    ]:
        t_upper = tgt.upper()
        test_feat_path = os.path.join(FEAT_DIR, f"test_features_{tgt}.tsv")
        out_path = os.path.join(PROC_DIR, f"test_pair_predictions_{tgt}.tsv")

        if os.path.exists(out_path):
            print(f"\n  {t_upper}: Found existing predictions {out_path}, skipping.")
            continue

        print(f"\n  {t_upper}: Generating test features...")
        generate_features_sql(con, cand_path, s1_tbl, tgt_tbl, is_s3, test_feat_path, has_label=False)

        print(f"  {t_upper}: Scoring...")
        t0 = time.time()

        # Load test features in chunks
        col_expr = ", ".join([f"CAST({c} AS DOUBLE) AS {c}" for c in FEATURE_NAMES])
        test_data = con.execute(f"""
            SELECT
                source1_entity_id,
                matched_entity_id,
                {col_expr}
            FROM read_csv('{test_feat_path}', delim='\\t', header=true)
        """).fetchnumpy()

        test_s1_ids = test_data["source1_entity_id"]
        test_t_ids = test_data["matched_entity_id"]
        X_test = np.column_stack([test_data[c].astype(np.float32) for c in FEATURE_NAMES])

        scores = model.predict(X_test)

        # Write predictions
        with open(out_path, "w", encoding="utf-8") as f:
            f.write("source1_entity_id\tcandidate_entity_id\ttarget_source\tmodel_score\n")
            for i in range(len(scores)):
                f.write(f"{test_s1_ids[i]}\t{test_t_ids[i]}\t{t_upper}\t{scores[i]:.6f}\n")

        size_mb = os.path.getsize(out_path) / (1024 * 1024)
        print(f"    Scored {len(scores):,} pairs ({time.time() - t0:.1f}s, {size_mb:.1f} MB)")

        # Score distribution
        for pct in [10, 25, 50, 75, 90, 95, 99]:
            val = np.percentile(scores, pct)
            print(f"    p{pct}: {val:.4f}")
        above_50 = (scores >= 0.5).sum()
        above_30 = (scores >= 0.3).sum()
        print(f"    >=0.5: {above_50:,} ({above_50/len(scores)*100:.2f}%)")
        print(f"    >=0.3: {above_30:,} ({above_30/len(scores)*100:.2f}%)")

        del X_test, test_data, scores

    # ================================================================
    # Phase 8: Experiment record
    # ================================================================
    print("\n" + "="*60)
    print("PHASE 8: EXPERIMENT RECORD & HANDOFF")
    print("="*60)

    try:
        import subprocess
        git_sha = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=REPO, text=True).strip()
    except Exception:
        git_sha = "unknown"

    experiment = {
        "git_sha": git_sha,
        "model_type": "LightGBM",
        "model_config": lgb_params,
        "random_seed": SEED,
        "feature_list": FEATURE_NAMES,
        "feature_count": len(FEATURE_NAMES),
        "training_data": {
            "path": train_feat_path,
            "total_pairs": int(total),
            "positives": int(positives),
            "negatives": int(negatives),
            "positive_rate_pct": round(float(pos_rate), 4),
        },
        "candidate_strategy": "Strategy B (Rule A: country+prefix4+house UNION Rule B: country+exact_address)",
        "model_path": model_path,
        "test_output_s2": os.path.join(PROC_DIR, "test_pair_predictions_s2.tsv"),
        "test_output_s3": os.path.join(PROC_DIR, "test_pair_predictions_s3.tsv"),
        "runtime_seconds": round(time.time() - t_global, 1),
    }

    exp_path = os.path.join(REPORT_DIR, "model_experiment.json")
    with open(exp_path, "w", encoding="utf-8") as f:
        json.dump(experiment, f, indent=2)

    # Handoff markdown
    handoff_path = os.path.join(REPORT_DIR, "MODELING_HANDOFF.md")
    with open(handoff_path, "w", encoding="utf-8") as f:
        f.write(f"""# P2 Modeling Handoff

## Model
- **Type**: LightGBM (CPU, 500 rounds)
- **Features**: {len(FEATURE_NAMES)} features
- **Training pairs**: {total:,} (pos={positives:,}, neg={negatives:,}, rate={pos_rate:.4f}%)
- **Candidate Strategy**: Strategy B (Rule A: country+prefix4+house UNION Rule B: country+exact_address)

## Validation Metrics (15% stratified holdout)
- **PR-AUC**: {pr_auc:.4f}

### Threshold Analysis
| Threshold | Precision | Recall | F1 | F0.5 |
|-----------|-----------|--------|-----|------|
""")
        for tr in threshold_results:
            f.write(f"| {tr['threshold']:.2f} | {tr['precision']:.4f} | {tr['recall']:.4f} | {tr['f1']:.4f} | {tr['f0.5']:.4f} |\n")

        f.write(f"""
## Feature Importance (Top 10, by Gain)
| Feature | Gain |
|---------|------|
""")
        for fname, fgain in feat_imp[:10]:
            f.write(f"| {fname} | {fgain:.1f} |\n")

        f.write(f"""
## Output Files
| File | Description |
|------|-------------|
| `P2/models/lgbm_baseline_v1.txt` | Trained LightGBM model |
| `P2/data/processed/test_pair_predictions_s2.tsv` | Test S2 scored predictions |
| `P2/data/processed/test_pair_predictions_s3.tsv` | Test S3 scored predictions |
| `P2/reports/error_analysis.tsv` | Validation error analysis |
| `P2/reports/model_experiment.json` | Full experiment record |
| `P2/data/features/train_features_combined.tsv` | Combined training features |

## Notes
- To prevent OOM during model training, negative examples were randomly downsampled to ~33% during memory loading. Positives were kept at 100%. The full candidate TSV (`train_features_combined.tsv`) still contains all 35.5M rows.
- No final production threshold declared. Evidence provided for Person 3 to decide.
- No test labels available; test outputs contain scores only.
- Final `matching_results.tsv` construction is owned by Person 3.
- Blocking recall at Strategy B level: S2=54.22%, S3=53.27%. Model can only score pairs in the candidate set.

## Git SHA
`{git_sha}`
""")

    print(f"  Experiment JSON: {exp_path}")
    print(f"  Handoff doc: {handoff_path}")

    con.close()
    total_time = time.time() - t_global
    print(f"\n{'='*60}")
    print(f"ALL PHASES COMPLETE ({total_time:.1f}s = {total_time/60:.1f}min)")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
